### ISSUE TITLE
factor value not supported to accept an array instead of a number

### ISSUE THREAD

**Issue by BrachiWeiss** [lazyee/flutter_ruler_picker#3]
Currently there is no possibility for the factor to be dynamic and not a fixed number.
For example - when the ruler is on numbers smaller than 1000 the factor will be 10.
and while scrolling-
that the ruler reaches a number greater than 1000 that the factor will change to 100
Thanks

**Comment by lazyee** [comment]
I added the `factorValue` attribute, you can try in `flutter_ruler_picker: ^1.0.4`

**Comment by BrachiWeiss** [comment]
Hi, thanks for the quick reply.

actually I meant to add the ability to create a ruler with segments.
 i.e. between values 10-1000 the factor will be 1,
 between 1000 -10,000 the factor will be 1000,
between 0-10 the factor will be 0.1, etc. 

note, that I need the scales to **visually** show different numbers in each ruler section,
as if there were few rulers connected to each other, each with its own factor. each starts off with the last value of the previous.

for that I would think of something like an optionally array of 'Segments' which each will include its own Range and factor
the default will be of course one segment with 1 factor

**Comment by lazyee** [comment]
Sorry I misunderstood your meaning, in fact this function is not common, but I am very interested in adding this function, waiting for my good news

**Comment by lazyee** [comment]
Done.  you can try in `flutter_ruler_picker: ^1.0.5`
just like this:
```dart
 RulerPicker(
              ...
              onBuildRulerScaleText: (index, value) {
                return value.toInt().toString();
              },
              ranges: const [
                RulerRange(begin: 0, end: 10, scale: 0.1),
                RulerRange(begin: 10, end: 100, scale: 1),
                RulerRange(begin: 100, end: 1000, scale: 10),
                RulerRange(begin: 1000, end: 10000, scale: 100),
                RulerRange(begin: 10000, end: 100000, scale: 1000)
              ],
             ...
)
```
