### ISSUE TITLE
Feature Request: Option to show decimal value

### ISSUE THREAD

**Issue by Anas35** [lazyee/flutter_ruler_picker#5]
Thank you for creating this package. I would like to request a feature to show decimal values as well. I realize that this may require a significant change to the code, but I would be happy to help with the implementation.

**Comment by lazyee** [comment]
Maybe I have added the features you mentioned, you can try it in ` flutter_ruler_picker: ^1.0.5`

**Comment by Anas35** [comment]
Thank you! Working as expected 💙
