### ISSUE TITLE
Change Ranges values end value does not work properly. (Attached Screen Recording)

### ISSUE THREAD

**Issue by Syed-Usama-Waqas** [lazyee/flutter_ruler_picker#6]
[Screen Recording 2023-08-27 at 8.13.22 PM.zip](https://github.com/lazyee/flutter_ruler_picker/files/12448286/Screen.Recording.2023-08-27.at.8.13.22.PM.zip)

**Comment by lazyee** [comment]
```dart
ranges:selected == 1? const [RulerRange(begin:20,end:200,scale:1)] : const [RulerRange(begin:40,end:400,scale:1)]
```
try it.😊

**Comment by Syed-Usama-Waqas** [comment]
> ```dart
> ranges:selected == 1? const [RulerRange(begin:20,end:200,scale:1)] : const [RulerRange(begin:40,end:400,scale:1)]
> ```
> 
> try it.😊



> ```dart
> ranges:selected == 1? const [RulerRange(begin:20,end:200,scale:1)] : const [RulerRange(begin:40,end:400,scale:1)]
> ```
> 
> try it.😊

Thanks for reply But this solution did not work.
I think there is some issue with package that is some kind of caching previous ranges maybe idk.

**Comment by lazyee** [comment]
I tried to understand your issue and made an attempt to fix it. Now you can try  
```dart 
flutter_ruler_picker:1.0.6 
```
